#!/usr/bin/env python
# encoding: utf-8


"""Project Euler, Problem 2.

https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms
will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do
not exceed four million, find the sum of the even-valued terms.
"""

import unittest
from euler.helpers import first, below, even


def fibonacci(a=1, b=2):
    """Infinite Fibonacci sequence generator."""
    while True:
        yield a
        a, b = b, b+a


class Problem2(unittest.TestCase):

    def test_validate_against_given_example(self):
        terms = first(10, fibonacci())
        self.assertTupleEqual((1, 2, 3, 5, 8, 13, 21, 34, 55, 89), tuple(terms))


def main():
    return sum(even(below(4000000, fibonacci())))


if __name__ == "__main__":
    unittest.main()

